### ISSUE TITLE
Add "update-only" command to "deploy.sh" and change .travis.yml to use it

### ISSUE THREAD

**Issue by rstata** [tim77code/limbo#15]
The Travis deploy automation will launch the limbo-travisci bot when we push changes onto the master branch.  We probably don't want that.  Do we?  If not, it would be easy to add logic to deploy.sh to prevent it from happening.

**Comment by davidchaiken** [comment]
Updating a running bot is in keeping with continuous deployment, especially if the bot can be upgraded without downtime.  Launching a bot that is not currently running is a boundary case.  It seems like the bot should not be launched, but should be upgraded.

**Comment by rstata** [comment]
Good point.  In fact, this should be true for all bots, not just limbo-travisci.  I updated the title of this issue to reflect the new objective.
